test page for lesson 1 (fixes: #172)
earthowned/planetfarms pull request #173
Opened 2021-05-11 12:41 UTC by SujalLama

2021-05-12 04:38 UTC, lmmrssa requested changes
UI not good for selection
![image](https://user-images.githubusercontent.com/2909490/117919070-1815e680-b30c-11eb-9036-605c59d0aa3f.png)

2021-05-13 15:24 UTC, lmmrssa approved these changes

2021-05-13 15:52 UTC, dogi approved these changes

2021-05-13 15:59 UTC, lmmrssa approved these changes

2021-05-13 16:02 UTC, merged