enterprises and group refactor
earthowned/planetfarms pull request #185
Opened 2021-05-13 15:20 UTC by dixitsigdel8

2021-05-19 15:00 UTC, lmmrssa requested changes

2021-05-20 16:38 UTC, lmmrssa requested changes
Due to change in class from **.collection-modal-inner-container** to **.collection-modal-inner-course-container** done on main branch UI is broken so please check this @SujalLama 
![image](https://user-images.githubusercontent.com/2909490/119016622-e232cb00-b9b9-11eb-81a7-5e515e2e6df5.png)

2021-05-21 06:41 UTC, lmmrssa approved these changes

2021-05-21 06:46 UTC, dogi approved these changes

2021-05-21 08:48 UTC, merged