pagination-design (fixes: #204)
earthowned/planetfarms pull request #205
Opened 2021-05-18 06:05 UTC by SujalLama

![pagination-btn](https://user-images.githubusercontent.com/71555740/118599433-39287c80-b7cf-11eb-87d3-aa662fd64550.JPG)

2021-05-18 15:36 UTC, lmmrssa requested changes
Pages should only show up if there that items to meet that page. Right now page number show up even if it is only 2 pages
![image](https://user-images.githubusercontent.com/2909490/118680922-e1196680-b81e-11eb-9f3b-5842f238f917.png)

2021-05-19 15:56 UTC, lmmrssa requested changes
Color for green button text should be same for prev, next and number
Do not show lot of numbers just show near by numbers from current page and first and last page number
![image](https://user-images.githubusercontent.com/2909490/118844535-c01e4780-b8ea-11eb-8e5e-70f156c76689.png)

2021-05-19 15:56 UTC, lmmrssa commented on src/Screens/Login/LoginScreen.jsx
> +    // try {
this is not to be touched here

2021-05-21 07:06 UTC, dogi approved these changes

2021-05-21 09:21 UTC, lmmrssa approved these changes

2021-05-21 09:43 UTC, merged