arrow functionality in dashboard (fixes: #212)
earthowned/planetfarms pull request #213
Opened 2021-05-19 12:55 UTC by SujalLama

2021-05-20 15:22 UTC, lmmrssa requested changes
Create separate component for tiles, this component is too big now
Also there should not be need for scroll event for all tiles There should be one common component with slider feature

2021-05-24 08:19 UTC, SujalLama commented
I have refactored the scroll components. I also have created custom hooks for scrolling functionality.

2021-05-24 15:19 UTC, lmmrssa requested changes
Looks better now still back arrow take directly to first element. it should behave similar to front arrow only going back visible screen scroll only.

2021-05-25 16:08 UTC, lmmrssa approved these changes

2021-05-26 04:46 UTC, dogi approved these changes

2021-05-26 04:49 UTC, dogi approved these changes

2021-05-26 05:34 UTC, merged