replace png with svg (issue #5  fixes)
earthowned/planetfarms pull request #25
Opened 2021-04-07 10:08 UTC by dixitsigdel8

issue #5  fix

2021-04-07 16:01 UTC, lmmrssa commented on src/Components/MessageRightComponent/MessageRightComponent.jsx
>                   <li className="messenger-list-item" onClick={() => makeCall()}><img src="./img/person-add.png"></img></li>
does it also needs to change?

2021-04-07 16:02 UTC, lmmrssa commented on src/Components/Logo/Logo.jsx
> +          <img className="logo-img" src="/img/logo.svg" alt="logo.svg"  />
alt should not be image name itself

2021-04-07 16:24 UTC, lmmrssa requested changes
Remove png files if there are not used other places

2021-04-09 02:40 UTC, lmmrssa approved these changes

2021-04-09 03:32 UTC, dogi approved these changes

2021-04-09 03:35 UTC, merged