css fix: community-group (fixes: #262)
earthowned/planetfarms pull request #267
Opened 2021-06-10 11:14 UTC by SujalLama

2021-06-11 04:42 UTC, lmmrssa approved these changes

2021-06-11 05:43 UTC, lmmrssa requested changes
Page is still not responsive http://localhost:3000/community-group-view-page/1

2021-06-11 05:47 UTC, lmmrssa commented
Also mobile view should look like this
![image](https://user-images.githubusercontent.com/2909490/121637026-86370000-caa8-11eb-945d-28ab30c5fd98.png)

2021-06-15 05:34 UTC, lmmrssa approved these changes

2021-06-15 06:34 UTC, dogi approved these changes

2021-06-15 06:35 UTC, merged