Userinfo responsive (fixes: #264 )
earthowned/planetfarms pull request #269
Opened 2021-06-10 13:19 UTC by SujalLama

2021-06-11 04:47 UTC, lmmrssa requested changes

2021-06-11 04:47 UTC, lmmrssa commented on src/Screens/CabinetUserInfo/CabinetUserInfo.jsx
> +            <img className='or-icon user-info-or-icon' src='/img/or.svg' alt='or icon' />
This can be text with background image of ---- no need for text to be in image

2021-06-11 04:47 UTC, lmmrssa commented on src/Screens/CabinetUserInfo/cabinet-user-info.css
> +
extra spacing

2021-06-11 04:47 UTC, lmmrssa commented on src/Screens/CabinetUserInfo/cabinet-user-info.css
> +}
need end of line

2021-06-11 04:47 UTC, lmmrssa commented on public/img/Coinbase.svg
> +<svg width="122" height="28" viewBox="0 0 122 28" fill="none" xmlns="http://www.w3.org/2000/svg">
naming convention not followed

2021-06-11 04:47 UTC, lmmrssa commented on src/Screens/CabinetUserInfo/CabinetUserInfo.jsx
> +import React from 'react'
naming convention of folder name not followed

2021-06-15 05:03 UTC, lmmrssa requested changes
There is space so these buttons can be on single line instead of breaking line
![image](https://user-images.githubusercontent.com/2909490/121995756-34071f00-cdc7-11eb-97da-01b478bfa46b.png)

2021-06-16 17:28 UTC, dogi approved these changes

2021-06-18 07:25 UTC, lmmrssa approved these changes

2021-06-18 07:44 UTC, dogi approved these changes

2021-06-18 07:47 UTC, merged