card-layout css and jsx refactor (fixes: #275)
earthowned/planetfarms pull request #276
Opened 2021-06-14 12:09 UTC by SujalLama

2021-06-15 04:55 UTC, lmmrssa approved these changes

2021-06-15 05:55 UTC, lmmrssa requested changes
Design of some pages got destroyed from before. Please check all pages once and fix if found issue with any other card pages
http://localhost:3000/courses/users
http://localhost:3000/courses/my-courses
http://localhost:3000/library/collection/users

2021-06-15 05:59 UTC, lmmrssa commented
This page should also use same card concept
![image](https://user-images.githubusercontent.com/2909490/122000729-06be6f00-cdcf-11eb-8bea-04422cb05400.png)

2021-06-15 16:37 UTC, lmmrssa commented
http://localhost:3000/courses/my-courses
![image](https://user-images.githubusercontent.com/2909490/122090380-6ea0a400-ce27-11eb-8f94-ee7f489b659a.png)
http://localhost:3000/community-members
![image](https://user-images.githubusercontent.com/2909490/122090499-89731880-ce27-11eb-9eeb-e57344c66236.png)

2021-06-18 14:32 UTC, lmmrssa approved these changes

2021-06-18 14:32 UTC, lmmrssa approved these changes

2021-06-18 14:32 UTC, lmmrssa approved these changes

2021-06-18 15:14 UTC, dogi approved these changes

2021-06-18 15:30 UTC, merged