Test api implementation (fixes: #301)
earthowned/planetfarms pull request #305
Opened 2021-07-09 12:31 UTC by SujalLama

Fixes #301

### Description
Used modal of TestAdd to create new screen for adding test
Made changes to api of test, user_test and questions
Now user can take test based on token of the user
Showing test results of user_test

### Screenshots
![testresult](https://user-images.githubusercontent.com/71555740/125077507-e5f0ed00-e0e0-11eb-943f-1d70ef9ea5c8.JPG)

//add test or edit test in the lesson view
![edit test](https://user-images.githubusercontent.com/71555740/125077912-631c6200-e0e1-11eb-83fd-ef419b2b0655.JPG)
![add test](https://user-images.githubusercontent.com/71555740/125077751-2b151f00-e0e1-11eb-9aa4-1bd90d98c834.JPG)

### Links and Curls

2021-07-12 06:37 UTC, lmmrssa requested changes
Seeing this error while trying to add test
![image](https://user-images.githubusercontent.com/2909490/125241845-b2de7180-e30b-11eb-8006-bf363350b7ea.png)
Also space is not covered completely. May be showing two option in a row could cover it for bigger screen

2021-07-20 18:11 UTC, lmmrssa commented
Test is not using full screen
Correct answer does not show
Button is coming two line
When clicking on back it gives popup and does nothing and gives error
![image](https://user-images.githubusercontent.com/2909490/126373944-ca7e7d3a-651a-4b01-9284-6d55f22d1072.png)

2021-07-20 18:32 UTC, dogi commented
@SujalLama thanks for the nice PR description

2021-07-20 18:35 UTC, dogi approved these changes

2021-07-20 18:35 UTC, lmmrssa approved these changes

2021-07-20 18:38 UTC, merged