Private route creation and refresh token functionality
earthowned/planetfarms pull request #312
Opened 2021-07-12 12:28 UTC by ABee-Tech

Fixes #issue_number

### Description
Description of changes made.

### Screenshots

### Links and Curls

2021-07-14 16:49 UTC, lmmrssa requested changes

2021-07-14 16:49 UTC, lmmrssa commented on src/actions/userAction.js
> +          Auth.currentSession().then((res) => {
this code is right now only checking cognito refresh not local refresh

2021-07-15 16:34 UTC, dogi approved these changes

2021-07-16 04:18 UTC, lmmrssa approved these changes

2021-07-16 04:20 UTC, merged