image resizer
earthowned/planetfarms pull request #332
Opened 2021-07-17 10:18 UTC by thepuskar

Fixes #issue_number

### Description
Description of changes made.

### Screenshots

### Links and Curls

2021-07-17 14:55 UTC, lmmrssa requested changes
Please use converted image on display as well

2021-07-18 15:51 UTC, lmmrssa requested changes
It still does not implemented in all places of course. Course creation and all other coverimage or photos.

2021-07-18 15:53 UTC, lmmrssa commented
Sample of places not using webp
![image](https://user-images.githubusercontent.com/2909490/126073752-0fffd113-7fb1-4669-ab56-0737d6916971.png)
![image](https://user-images.githubusercontent.com/2909490/126073757-76fa388a-7bb4-4b52-8981-b02da9491ea1.png)
![image](https://user-images.githubusercontent.com/2909490/126073771-c29565c6-50fd-4ea9-a9a0-c86906f5b0c6.png)

2021-07-20 16:49 UTC, lmmrssa approved these changes

2021-07-20 17:51 UTC, dogi approved these changes

2021-07-20 18:16 UTC, merged