group and enterprise subheader
earthowned/planetfarms pull request #351
Opened 2021-07-18 12:47 UTC by SujalLama

Fixes #326 

### Description
Description of changes made.
subheader of group and enterprise is resolved

### Screenshots

previously: both enterprise and group had same design
![enterprise](https://user-images.githubusercontent.com/71555740/126067543-28b7c614-2462-4f18-a03e-99cc4ea6ee7e.JPG)

### Links and Curls
http://localhost:3000/community-group/${communityname}
http://localhost:3000/enterprises/{communityname}

2021-07-18 16:31 UTC, lmmrssa requested changes
On mobile view it is changing to filter by so there are two filter by

2021-07-19 15:24 UTC, lmmrssa commented
Course page now looks like this
![image](https://user-images.githubusercontent.com/2909490/126185111-1623419f-5278-47ee-8266-88ac8bc43de5.png)

2021-07-19 16:04 UTC, lmmrssa requested changes
there is also history change and console
also linting of css is off

2021-07-20 16:31 UTC, lmmrssa approved these changes

2021-07-20 17:15 UTC, dogi approved these changes

2021-07-20 18:40 UTC, merged