permission based on role (fixes: #386)
earthowned/planetfarms pull request #398
Opened 2021-07-26 12:27 UTC by SujalLama

Fixes #386 

### Description
added role column to the users table
added permission middleware to the category route to authorize

### Screenshots

### Links and Curls
src/middleware/permission.js
src/migrations/20210726115631-alter_users_add_role.js
src/models/userModel.js
src/routes/categoriesRouter.js

2021-07-28 15:41 UTC, lmmrssa requested changes

2021-07-28 15:41 UTC, lmmrssa commented on api/src/routes/categoriesRouter.js
> +router.route('/:id').get(getSingleCategory).put(protect, permit('sysadmin'), updateCategory).delete(protect, permit('sysadmin'), deleteCategory)
this should be able to accept multiple roles

2021-07-28 15:41 UTC, lmmrssa commented on src/components/table/Table.jsx
> +                            property.map((propKey, index) => {
indentation off

2021-07-28 15:41 UTC, lmmrssa commented on src/components/table/Table.jsx
> +                                        property.map((propkey, index) => {
identation off

2021-07-28 15:41 UTC, lmmrssa commented on src/screens/category/Category.jsx
> +  if (role !== 'sysadmin') {
this should be controlled by permission not here

2021-07-28 15:41 UTC, lmmrssa commented on src/screens/category/Category.jsx
> +  const config = configFunc()
this is not required to be used here should use getApi function instead of axios.get

2021-07-28 15:41 UTC, lmmrssa commented on src/components/table/Table.jsx
> +            <th>S.N.</th>
columns for table should be passed as some table might not have SN or option or might have to just show few columns not all columns of record.
In category case updated and created date are not required

2021-07-30 08:17 UTC, dogi approved these changes

2021-07-30 08:50 UTC, lmmrssa approved these changes

2021-07-30 09:01 UTC, merged