file type validation
earthowned/planetfarms pull request #400
Opened 2021-07-26 16:23 UTC by thepuskar

Fixes #issue_number

### Description
Description of changes made.

### Screenshots

### Links and Curls

2021-07-28 15:20 UTC, lmmrssa requested changes

2021-07-28 15:20 UTC, lmmrssa commented on src/utils/apiFunc.jsx
> +export const postCourseAPI = async (url, data, header) => {
this is just creating new function where postApi is already doing same

2021-07-28 15:20 UTC, lmmrssa commented on src/utils/apiFunc.jsx
> +  const headers = { 'Content-Type': header || 'application/json' }
in future other header parameters might also be changed so this has been made too specific. it should merge default headers and header passed

2021-07-28 15:20 UTC, lmmrssa commented on src/actions/lessonActions.js
> +          },
all these are still not using common postApi

2021-07-28 15:20 UTC, lmmrssa commented on api/src/middleware/errorHandler.js
> +const multer = require('multer')
dont see multer used in file

2021-07-28 15:20 UTC, lmmrssa commented on api/src/controllers/photoController.js
> +  console.log(res.status)
this code can be removed

2021-07-28 15:20 UTC, lmmrssa commented on api/src/server.js
> +
no need of this extra empty line

2021-07-29 16:56 UTC, lmmrssa approved these changes

2021-07-30 06:39 UTC, dogi approved these changes

2021-07-30 06:41 UTC, merged