Member profile page (fixes: #402)
earthowned/planetfarms pull request #404
Opened 2021-07-27 08:03 UTC by SujalLama

Fixes #402 

### Description
Single component for myprofile and communitymemberprofile
Delete member profile component
back button works now
Edit button for my profile and follow button for community member

### Screenshots

### Links and Curls
deleted:
src/screens/communityMemberProfile/CommunityMemberProfile.jsx
src/screens/communityMemberProfile/CommunityMemberProfile.scss

modified:
src/App.jsx
src/screens/dashboard/MyProfile.jsx

routes: 
http://localhost:3000/community-members-profile/2
http://localhost:3000/myProfile

2021-07-28 15:32 UTC, lmmrssa requested changes

2021-07-28 15:32 UTC, lmmrssa commented on src/App.jsx
> +            <PrivateRoute component={MyProfile} path='/community-members-profile/:id' exact />
url should be generic as it is general profile page not specific to community

2021-07-28 15:32 UTC, lmmrssa commented on src/screens/dashboard/MyProfile.jsx
> +  const { userInfo } = userLogin
this is current logged in user and not sure this is required as it was not being sued before and getMyDetails was getting details details for user profile

2021-07-28 15:32 UTC, lmmrssa commented on src/screens/dashboard/MyProfile.jsx
> +                : 'Community Members'
This is actually User profile not community members

2021-07-28 15:32 UTC, lmmrssa commented on src/screens/dashboard/MyProfile.jsx
> +                      follow={pathname !== '/myProfile'}
follow should not show if logged in user and current profile is not same irrespective of url

2021-08-13 12:39 UTC, lmmrssa approved these changes

2021-08-13 17:37 UTC, dogi commented
![image](https://user-images.githubusercontent.com/13684059/129398015-972bde39-864f-4e62-96b0-6830a275f7a0.png)
removing phone number -> undefined

2021-08-13 17:37 UTC, dogi approved these changes

2021-08-13 18:10 UTC, merged