lesson progress
earthowned/planetfarms pull request #412
Opened 2021-07-30 11:06 UTC by thepuskar

Fixes #issue_number

### Description
Description of changes made.

### Screenshots

### Links and Curls

2021-08-03 16:06 UTC, lmmrssa requested changes
seems like lesson_progress is not being saved. also lesson 1 should only be active once user join the course.

2021-08-11 16:06 UTC, lmmrssa requested changes
@thepuskar seems like lesson progress is only saved when test is taken. it should save when course lesson is visited and mark as complete when test done
For lesson without test next button is not enabled

2021-08-12 16:47 UTC, lmmrssa requested changes

2021-08-12 16:47 UTC, lmmrssa commented on src/components/myCoursesCard/courseDescription/LessonCourseSingle.jsx
> +    const addProgress = () => {
seems like this is still WIP as addProgress is not being called so it does not seem to record or navigate to lesson

2021-08-16 15:39 UTC, lmmrssa commented
@SujalLama process is still not working as expected. It is saving progress when course is viewed not on lesson

2021-08-25 07:49 UTC, dogi approved these changes
@SujalLama @thepuskar @lmmrssa congrats :P

2021-08-25 07:57 UTC, lmmrssa approved these changes

2021-08-25 08:00 UTC, merged