Update README.md
earthowned/planetfarms pull request #68
Opened 2021-04-16 06:31 UTC by robinGiri

issue: #64

2021-04-16 06:48 UTC, dogi requested changes
good start ;)

2 things are missing:

- `docker-compose up -d`
- `npx ...`

2021-04-20 16:36 UTC, robinGiri commented
Thanks @dogi  for reminding. I have added information about docker-composer as well as database migration hope you will like it.
Thanks again for your review.

2021-04-22 18:13 UTC, dogi approved these changes

2021-04-23 10:34 UTC, lmmrssa approved these changes

2021-04-23 10:34 UTC, merged